[general]
import = ["~/.config/alacritty/current_theme.toml"]
live_config_reload = true

[scrolling]
history = 1000

[env]
TERM = "xterm-256color"

[window]
padding.x = 20
padding.y = 10
decorations = "none"

[font]
normal.family = "JetBrainsMonoNL Nerd Font"
bold.family = "JetBrainsMonoNL Nerd Font"
italic.family = "JetBrainsMonoNL Nerd Font"
bold_italic.family = "JetBrainsMonoNL Nerd Font"
size = 18.0
builtin_box_drawing = false
offset.x = 0
offset.y = 1

[selection]
save_to_clipboard = true

[keyboard]
bindings = [{ key = "Return", mods = "Command", action = "ToggleFullscreen" }]
