palette = "melange"

command_timeout = 3600

"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
 ➜\
$directory\
${custom.giturl}\
$git_branch\
$git_state\
$git_status\
$line_break\
$character
"""

right_format = """$all"""

[directory]
style = "yellow"
format = "[ $path ]($style)"
#truncation_length = 4
#truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[custom.giturl]
description = "Display symbol for remote Git server"
command = """
GIT_REMOTE=$(command git ls-remote --get-url 2> /dev/null)
if [[ "$GIT_REMOTE" =~ "github" ]]; then
    GIT_REMOTE_SYMBOL=" "
elif [[ "$GIT_REMOTE" =~ "gitlab" ]]; then
    GIT_REMOTE_SYMBOL=" "
elif [[ "$GIT_REMOTE" =~ "bitbucket" ]]; then
    GIT_REMOTE_SYMBOL=" "
elif [[ "$GIT_REMOTE" =~ "git" ]]; then
    GIT_REMOTE_SYMBOL=" "
else
    GIT_REMOTE_SYMBOL=" "
fi
echo "$GIT_REMOTE_SYMBOL "
"""
when = 'git rev-parse --is-inside-work-tree 2> /dev/null'
format = "at $output"

[git_branch]
symbol = "[](base) "
# format =  ' [$symbol$branch(:$remote_branch)]($style)[]'
style = "fg:mauve bg:base"
format = '  on[$symbol$branch]($style)[](base)'

[git_status]
format = ' [($all_status$ahead_behind )]($style)'

[nodejs]
symbol = ""
format = ' [$symbol $version]($style) '
style = "fg:#689d6a"

[c]
symbol = " "
format = " [$symbol$version]($style) "
style = "fg:#a8b9cc"

[custom.cpp]
detect_extensions = ['cpp', 'cc', 'hpp']
symbol = "󰙲 "
format = " [$symbol(v$output)]($style) "
command = "clang++ --version | awk '/clang version/{print $4}'"
disabled = false
ignore_timeout = false
style = "fg:#00599c"

[rust]
symbol = ""
format = ' [$symbol $version]($style) '
style = "fg:#dea584"

[golang]
symbol = ""
format = ' [$symbol $version]($style) '
detect_files = ["go.mod"]
style = "fg:#00add8"

[python]
symbol = ""
format = ' [$symbol $version]($style) '
style = "fg:#3776ab"

[zig]
symbol = '↯'
format = " [$symbol $version]($style) "
style = "fg:#f7a41d"

[cmake]
symbol = "△"
format = " [$symbol $version]($style) "
style = "fg:#064f8c"

[docker_context]
symbol = ""
format = ' [$symbol $context]($style) '
style = "fg:#384d54"

[package]
symbol = '󰏗 '
style = "fg:#ff8833"

[lua]
symbol = ' '
style = "fg:#00007c"

[time]
disabled = true
time_format = "%R"
style = "bg:peach"
format = '[[  $time ](fg:mantle bg:foam)]($style)'

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[❯](bold fg:#a9dc76)'
error_symbol = '[❯](bold fg:#ff6188)'
vimcmd_symbol = '[❮](bold fg:#78dce8)'
vimcmd_replace_one_symbol = '[❮](bold fg:#ab9df2)'
vimcmd_replace_symbol = '[❮](bold fg:#ab9df2)'
vimcmd_visual_symbol = '[❮](bold fg:#ffd866)'

[palettes.melange]
base     = "#292522"
mantle   = "#34302C"
text     = "#ece1d7"
subtext0 = "#867462"
surface  = "#403a36"
overlay  = "#34302c"
red      = "#BD8183"
green    = "#78997A"
yellow   = "#E49B5D"
blue     = "#7F91B2"
mauve    = "#B380B0"
teal     = "#7B9695"
peach    = "#D47766"
foam     = "#89B3B6"
gold     = "#EBC06D"