set -g default-terminal "screen-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Prefix
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Sort sessions by name
bind s choose-tree -sZ -O name

# Starting index
set -g base-index 1
setw -g pane-base-index 1

# Keymaps
unbind %
bind | split-window -h -c "#{pane_current_path}" 

unbind '"'
bind - split-window -v -c "#{pane_current_path}"

unbind v
bind v copy-mode

unbind r
bind r source-file ~/.config/tmux/tmux.conf

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

bind -r m resize-pane -Z

set -g mouse on

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

bind-key n command-prompt "new-session -s '%%'"

unbind -T copy-mode-vi MouseDragEnd1Pane

# Plugins
set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-online-status'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-sessionist'

# Tmux resurrect config
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-dir '~/.config/tmux/resurrect'
bind-key C-c run-shell "rm -r ~/.config/tmux/resurrect/*; tmux display 'Resurrect dir cleaned!'"

# Continuum config
set -g @continuum-restore 'off'

set -g @online_icon "on"
set -g @offline_icon "off"

set -g @batt_icon_charge_tier8 '█'
set -g @batt_icon_charge_tier7 '▇'
set -g @batt_icon_charge_tier6 '▆'
set -g @batt_icon_charge_tier5 '▅'
set -g @batt_icon_charge_tier4 '▄'
set -g @batt_icon_charge_tier3 '▃'
set -g @batt_icon_charge_tier2 '▂'
set -g @batt_icon_charge_tier1 '▁'
set -g @batt_icon_status_charged '█'
set -g @batt_icon_status_charging '↯'

source-file "~/.config/tmux/themes/melange.conf" # iris-theme
run '~/.config/tmux/plugins/tpm/tpm' 